# ============================================
# MySQL Password Change Job
# ============================================
# One-time job to change MySQL passwords from old values to GitHub Secrets
# Run this after updating secrets in deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-password-change
  namespace: beliv-apartment
  labels:
    app: apartment-system
    component: database-maintenance
spec:
  # Keep job history for debugging
  ttlSecondsAfterFinished: 300  # Delete after 5 minutes
  backoffLimit: 3  # Retry up to 3 times on failure
  
  template:
    metadata:
      labels:
        app: apartment-system
        component: database-maintenance
    spec:
      restartPolicy: Never
      
      containers:
      - name: mysql-password-changer
        image: mysql:8.0
        
        env:
        # Old passwords (hardcoded for one-time migration)
        - name: OLD_ROOT_PASSWORD
          value: "secure_root_password_change_me"
        - name: OLD_USER_PASSWORD
          value: "secure_password_change_me"
        
        # New passwords from GitHub Secrets
        - name: NEW_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: NEW_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          echo "===================================="
          echo "MySQL Password Change Job Started"
          echo "===================================="
          
          # Wait for MySQL to be ready
          echo "Waiting for MySQL service to be ready..."
          until mysql -h mysql-service -uroot -p${OLD_ROOT_PASSWORD} -e "SELECT 1" &>/dev/null; do
            echo "MySQL not ready yet, waiting..."
            sleep 5
          done
          
          echo "✅ MySQL is ready, proceeding with password change..."
          
          # === BACKUP CURRENT STATE ===
          echo "Creating backup of current passwords..."
          mysql -h mysql-service -uroot -p${OLD_ROOT_PASSWORD} <<EOF > /tmp/password-backup.sql
          -- Backup created: $(date)
          -- Old root password: ${OLD_ROOT_PASSWORD}
          -- Old user password: ${OLD_USER_PASSWORD}
          SELECT CONCAT('-- User: ', User, '@', Host) as backup_info FROM mysql.user WHERE User IN ('root', '${MYSQL_USERNAME}');
          EOF
          
          echo "✅ Backup created at /tmp/password-backup.sql"
          echo "⚠️  To restore: Use old passwords in Job definition and re-run"
          
          # Decode base64 passwords (they are stored as base64 in secrets)
          NEW_ROOT_PASS=$(echo ${NEW_ROOT_PASSWORD} | base64 --decode)
          NEW_USER_PASS=$(echo ${NEW_USER_PASSWORD} | base64 --decode)
          MYSQL_USERNAME=$(echo ${MYSQL_USER} | base64 --decode)
          
          echo "Changing passwords..."
          
          # Change root password
          mysql -h mysql-service -uroot -p${OLD_ROOT_PASSWORD} <<EOF
          -- Change root password for all hosts
          ALTER USER 'root'@'%' IDENTIFIED BY '${NEW_ROOT_PASS}';
          ALTER USER 'root'@'localhost' IDENTIFIED BY '${NEW_ROOT_PASS}';
          
          -- Change application user password
          ALTER USER '${MYSQL_USERNAME}'@'%' IDENTIFIED BY '${NEW_USER_PASS}';
          
          -- Apply changes
          FLUSH PRIVILEGES;
          
          -- Verify changes
          SELECT User, Host FROM mysql.user WHERE User IN ('root', '${MYSQL_USERNAME}');
          EOF
          
          if [ $? -eq 0 ]; then
            echo "✅ Password change completed successfully!"
            
            # Test new passwords
            echo "Testing new root password..."
            mysql -h mysql-service -uroot -p${NEW_ROOT_PASS} -e "SELECT 'Root password works!' as Status;"
            
            echo "Testing new user password..."
            mysql -h mysql-service -u${MYSQL_USERNAME} -p${NEW_USER_PASS} -e "SELECT 'User password works!' as Status;"
            
            echo "===================================="
            echo "✅ All passwords changed and verified!"
            echo "===================================="
          else
            echo "❌ Password change failed!"
            exit 1
          fi
