# ============================================
# DATABASE CREDENTIALS SECRET
# ============================================
# Contains MySQL root password, database name, user, and password
# NOTE: In production, use proper secret management (Sealed Secrets, External Secrets Operator, etc.)
# 
# To update values:
# echo -n 'your-value' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: beliv-apartment
  labels:
    app: apartment-system
    component: database
type: Opaque
data:
  # Default values (base64 encoded):
  # root-password: from GitHub Secret MYSQL_ROOT_PASSWORD
  # database: from GitHub Secret MYSQL_DATABASE
  # username: from GitHub Secret MYSQL_USERNAME
  # password: from GitHub Secret MYSQL_PASSWORD
  root-password: ${MYSQL_ROOT_PASSWORD}
  database: ${MYSQL_DATABASE}
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
